---
title: "Indicator visualizations with Plotly"
author: "Sean Hardison"
date: "September 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.align = "center",
                      message = FALSE,
                      warning = FALSE)
library(dplyr)
library(ggplot2)
library(plotly)
library(esrr)
library(cowplot)
library(sf)
library(ncdf4)
library(raster)
library(rgdal)
library(rpart)

soe <- read.csv("data/SOE_data_2018.csv") %>% filter(SOE.2018 == 'Y')
crs <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0" 
#get strata files to clip thermal habitat projections
strata <- readOGR("data/strata", verbose = F)
strata@proj4string <- CRS(crs)

Sys.setenv("plotly_username"="seanhardison")
Sys.setenv("plotly_api_key"="NZ7ySWIc383RvJdWEHH9")


```


```{r plotting functions}

get_trend <- function(v){

variable <- v
dat <- soe %>% filter(Var %in% variable)

out <- NULL
xmin <- NULL
for (i in 1:length(unique(dat$Var))){
  t <- dat[dat$Var == unique(dat$Var)[i],] 
  xmin[i] <- min(dat[dat$Var == unique(dat$Var)[i],]$Time)
  tlist <- gls.ms(t, "Value", "Time")
  
  trend <- tlist[[1]]$trend_line


  out_df <- data.frame(Trend = trend,
                    Var = unique(dat$Var)[i],
                    Time = dat[dat$Var == unique(dat$Var)[i],]$Time)
  
  assign('out', rbind(out_df,out))
  
}
 return(out)
}

```


```{r ggplot figs, eval = F}
#set up----------------------------------------------------------------------

variables <- c("Mid-Atlantic angler trips","Mid-Atlantic fleet count")
dat <- soe %>% filter(Var %in% variables)
xmin <- NULL
for (i in 1:length(unique(dat$Var))){
  xmin[i] <- min(dat[dat$Var == unique(dat$Var)[i],]$Time)
}
dat <- dat %>% filter(Time >= max(xmin))

#get trend
out <- get_trend(v = variables)

#split
d1 <- dat[dat$Var == unique(out$Var)[1],]
d2 <- dat[dat$Var == unique(out$Var)[2],]
#----------------------------------------------------------------------------  

var1 <- ggplot(d1, aes(x = Time, y = Value)) +
  geom_point()+
  geom_line() + 
  { if(all(!is.na(out[out$Var == unique(out$Var)[1],]$Trend)) &
       nrow(out[out$Var == unique(out$Var)[1],]) >= 30)
    geom_line(data = out[out$Var == unique(out$Var)[1],],
              aes(x = Time, y = Trend))
    } 
var2 <- ggplot(d2, aes(x = Time, y = Value)) +
  geom_point()+
  geom_line() + 
  { if(all(!is.na(out[out$var == unique(out$var)[2],]$trend)) &
       nrow(out[out$Var == unique(out$Var)[2],]) >= 30)
    geom_line(data = out[out$var == unique(out$var)[2],],
              aes(x = Time, y = Trend))
  } 

pg <- plot_grid(var1, var2, align = "v", nrow = 2)
pg


```
<br>
<br>
<br>

```{r plotly grid}

#set up----------------------------------------------------------------------
variables <- c("Mid-Atlantic angler trips","Mid-Atlantic fleet count")
dat <- soe %>% filter(Var %in% variables)
xmin <- NULL
for (i in 1:length(unique(dat$Var))){
  xmin[i] <- min(dat[dat$Var == unique(dat$Var)[i],]$Time)
}
dat <- dat %>% filter(Time >= max(xmin))

#get trend
out <- get_trend(v = variables)

#split
d1 <- dat[dat$Var == unique(out$Var)[1],]
d2 <- dat[dat$Var == unique(out$Var)[2],]
#----------------------------------------------------------------------------

y1 <- list(
  title = "Fleet count",
  range = c(15,50),
  showline = TRUE
)

y2 <- list(
  title = "Angler trips",
  range = c(0,30e6),
  showline = TRUE
)

xax <- list(
  title = "Time",
  showline = TRUE
)
var1 <- plot_ly(d1, x = ~Time, y = ~Value) %>%
  layout(xaxis = xax, yaxis = y1) %>%
  add_lines(showlegend = F, color = I("black")) %>%
  add_markers(showlegend = F, color = I("black"), name = 'Fleet count') 
   

var2 <- plot_ly(d2, x = ~Time, y = ~Value) %>%
  layout(xaxis = xax, yaxis = y2) %>%
  add_lines(showlegend = F, color = I("black")) %>%
  add_markers(showlegend = F, color = I("black"), name = 'Angler trips')
  
p <- subplot(var1, var2, titleX = T, titleY = T) %>% layout(title = "Mid-Atlantic Recreational Fishing")
shiny::div(p, align = "center")
```
<br>
<br>
<br>
```{r visualize scaled data}
tot.landings <- soe %>% filter(Units == "metric tons",!grepl("Total", Var), grepl("FMC",Var)) %>%
  group_by(EPU, Time) %>% 
  dplyr::summarise(epu_sum = sum(Value))

y1 <- list(
  title = "Commercial landings (metric tons)",
  showline = TRUE
)

xax = list(
  title = "Time",
  showline = FALSE
  
  )

var1 <- plot_ly(tot.landings, x = ~Time, y = ~epu_sum, color = ~EPU, colors = "Dark2") %>%
  add_lines() %>%
  layout(yaxis = y1, xaxis = xax, title = "Total Managed Landings by EPU", autosize = F, width = 650)

shiny::div(var1, align = "center")

```


```{r landings subplots, eval = F}
guild.landings <- soe %>% filter(Units == "metric tons",!grepl("Total", Var), grepl("FMC",Var), EPU == "MAB", Time >= 1986) %>%
  mutate(legend, legend = plyr::mapvalues(Var,
          from = c('Piscivore MAFMC managed species sea food MAB',
                 'Planktivore MAFMC managed species sea food MAB',
                 'Benthivore MAFMC managed species sea food MAB',
                 'Benthos MAFMC managed species sea food MAB'),
          to = c('Piscivore',
               'Planktivore',
               'Benthivore',
               'Benthos'))) 

guild.landings$legend <- ordered(guild.landings$legend, levels = c('Piscivore',
                                                             'Planktivore',
                                                             'Benthivore',
                                                             'Benthos'))

y1 <- list(
  title = paste0(c(rep("&nbsp;", 26),"Commercial landings (metric tons)", rep("&nbsp;", 1)), collapse = "")
)

xax = list(
  showline = T
)

p <- guild.landings %>%
  transform(id = as.integer(legend)) %>%
  plot_ly(x = ~Time, y = ~Value, color = ~legend,
          colors = "Dark2",
          yaxis = ~paste0("y", id)) %>%
  add_lines() %>% 
  subplot(nrows = 4, shareX = TRUE) %>%
  layout(yaxis3 = y1, xaxis = xax, title = "Mid-Atlantic Managed Landings by Feeding Guild")
shiny::div(p, align = "center")
```
<br>
<br>
<br>

```{r a different approach for ordering}

#get data and trends for plotting
variables <- c('Piscivore MAFMC managed species sea food MAB',
                 'Planktivore MAFMC managed species sea food MAB',
                 'Benthivore MAFMC managed species sea food MAB',
                 'Benthos MAFMC managed species sea food MAB')
guild.landings <- soe %>% filter(Units == "metric tons",!grepl("Total", Var), grepl("FMC",Var), EPU == "MAB", Time >= 1986) %>%
  mutate(Var, Var = plyr::mapvalues(Var,
          from = variables,
          to = c('Piscivore',
               'Planktivore',
               'Benthivore',
               'Benthos'))) %>% tidyr::spread(., key = Var, value = Value)

out <- get_trend(v = variables)
out <-  out %>% filter(Time >= 1986, !is.na(Trend)) %>%
  mutate(Var, Var = plyr::mapvalues(Var,
          from = variables,
          to = c('Piscivore',
               'Planktivore',
               'Benthivore',
               'Benthos'))) %>% tidyr::spread(., key = Var, value = Trend)

#set axes
y3 <- list(
  title = paste0(c(rep("&nbsp;", 26),"Commercial landings (metric tons)", rep("&nbsp;", 1)), collapse = ""),
  showline = T
)

xax = list(
  showline = T
)


#Plotting code
v1 <- plot_ly(guild.landings, x = ~Time, y = ~Piscivore, name = "Piscivore",
              type = 'scatter', mode = 'lines+markers', showlegend = T) %>%
  add_lines(name = "Trend",data = out, x = ~Time, y = ~Piscivore, color = I("purple"), showlegend = F)

v2 <- plot_ly(guild.landings, x = ~Time, y = ~Planktivore, name = "Planktivore",
              type = 'scatter', mode = 'lines+markers', showlegend = T)

v3 <- plot_ly(guild.landings, x = ~Time, y = ~Benthivore, name = "Benthivore",
              type = 'scatter', mode = 'lines+markers', showlegend = T) %>%
  add_lines(name = "Trend",data = out, x = ~Time, y = ~Benthivore, color = I("orange"), showlegend = F)

v4 <- plot_ly(guild.landings, x = ~Time, y = ~Benthos, name = "Benthos",
              type = 'scatter', mode = 'lines+markers', showlegend = T) %>%
  add_lines(name = "Trend",data = out, x = ~Time, y = ~Benthos, color = I("purple"), showlegend = F)

p <- subplot(v1, v2, v3, v4, shareX = T, nrows = 4) %>%
  layout(yaxis = list(showline = T), 
         yaxis2 = list(showline = T),
         yaxis3 = y3,
         yaxis4 = list(showline = T),
         xaxis4 = list(showline = T),
         title = "Mid-Atlantic Managed Landings by Feeding Guild",
         autosize = F,
         width = 650) 
shiny::div(p, align = "center")
```


```{r ggplotly facetting, eval = F}
guild.landings <- soe %>% filter(Units == "metric tons",!grepl("Total", Var), grepl("FMC",Var), EPU == "MAB", Time >= 1986) %>%
  mutate(Var, Var = plyr::mapvalues(Var,
          from = c('Piscivore MAFMC managed species sea food MAB',
                 'Planktivore MAFMC managed species sea food MAB',
                 'Benthivore MAFMC managed species sea food MAB',
                 'Benthos MAFMC managed species sea food MAB'),
          to = c('Piscivore',
               'Planktivore',
               'Benthivore',
               'Benthos'))) 

guild.landings$Var <- ordered(guild.landings$Var, levels = c('Piscivore',
                                                             'Planktivore',
                                                             'Benthivore',
                                                             'Benthos'))

p <- ggplot(data = guild.landings, aes(x = Time, y = Value/1000)) +
    ylab("") +
    xlab("") +
    geom_line() +
    geom_point() +
    facet_wrap(Var ~ ., nrow = 4, ncol = 1, scales = "free_y") +
    theme_bw() +
    theme(plot.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
    annotate("text", label = c("A","B","C","D"), x = 1989, y = Inf, vjust = 1.5, size = 5)

y3 <- list(
  title = paste0(c(rep("&nbsp;", 40),
         "Commercial landings (10<sup>3</sup> metric tons)",
         rep("\n&nbsp;", 50)),
       collapse = "")
)

p <- ggplotly(p)%>%
  layout(yaxis3 = y3,
         xaxis4 = xax)
shiny::div(p, align = "center")
```
<br>
<br>
<br>

```{r epu maps}



#North America
ne_countries <- rnaturalearth::ne_countries(scale = 10,
                                            continent = "North America",
                                            returnclass = "sf") %>%
  sf::st_transform(crs = crs)

#States
ne_states <- rnaturalearth::ne_states(country = "united states of america",
                                      returnclass = "sf") %>%
  sf::st_transform(crs = crs)

#EPU
EPU <- sf::st_read("data/EPU_Extended.shp", quiet = TRUE) %>%
  st_transform(., crs = crs)
EPU <- EPU[EPU$EPU != "SS" ,]

#Ocean
lseq = seq(20, 60, by=.25)
boundary <- data.frame(
  long = c(rep(-180, length(lseq)), rep(180, length(lseq)), -180),
  lat  = c(lseq, rev(lseq), lseq[1]))

#bbox
xmin = -76
xmax = -66
ymin = 36
ymax = 45

xlims <- c(xmin, xmax)
ylims <- c(ymin, ymax)

#Plot
p1 <- ggplot() +
  geom_polygon(data=boundary, aes(x=long, y=lat), fill="#9AC5E3") +
  geom_sf(data = ne_countries, fill = "white",color = "white", size = 0.25) +
  geom_sf(data = ne_states, fill = "white",color = "white", size = 0.05) +
  geom_sf(data = EPU, aes(fill = EPU), color = c('#0049EE','#25408F','#0068B5')) +
  scale_fill_manual(values = c('#0049EE','#25408F','#0068B5')) +
  coord_sf(crs = crs, xlim = xlims, ylim = ylims) +
  theme_map() +
  theme(legend.position = "right",
                 legend.key.width = ggplot2::unit(2, "cm"))


plt <- ggplotly(p1)%>%
    layout(
      title = "The Northeast Large Marine Ecosystem (NE-LME)",
      titlefont = list(size = 15),
      margin = list(b = 50, t = 50),
      autosize = F,
      width = 500,
      legend = list(x = 0.1, y = 0.9,
      bgcolor = "#E2E2E2",
      bordercolor = "#FFFFFF",
      borderwidth = 2)
    )

shiny::div(plt, align = "center")

```
<br>
<br>
<br>

```{r annual sst time series}
#get data
mab <- soe %>%
  filter(Var == "sst mean long term MAB" | Var == "sst sd long term MAB" | Var == "sst mean 2017 MAB") %>%
  tidyr::spread(., key = Var, value = Value) %>% 
  mutate(DOY = seq( as.Date("2017-01-01"), as.Date("2017-12-31"), by="+1 day"))

#custom x axis
xax <- list(
  autotick = F,
  title = "Month",
  tickmode = "array",
  tickvals = seq(50,350,100),
  ticktext = c("Feb","May","Sep","Dec")
)

#plot
p <- plot_ly(mab, x = ~DOY, y = ~`sst mean long term MAB`, name = 'Long-term mean SST', type = 'scatter', mode = 'lines',
        line = list(color = 'grey', width = 3)) %>%
  add_trace(y = ~`sst mean long term MAB` - `sst sd long term MAB`, name = '- 1 SD',
            line = list(color = 'rgb(22, 96, 167)', width = 1, showlegend = F)) %>%
  add_trace(y = ~`sst mean long term MAB` + `sst sd long term MAB`, name = '+ 1 SD',
            line = list(color = 'rgb(22, 96, 167)', width = 1, showlegend = F)) %>%
    add_trace(y = ~`sst mean 2017 MAB`, name = '2017 SST',
            line = list(color = 'red', width = 3, showlegend = F)) %>%
  layout(title = "SSTs in the Mid-Atlantic Bight",
         xaxis = xax,
         yaxis = list (title = "Temperature (&deg;C)"),
         legend = list(x = 0.1, y = 0.9))

shiny::div(p %>% layout(autosize = F, width = 650), align = "center")
```

<br>
<br>
<br>

```{r bsb thermal habitat}

#get data
data <- nc_open("data/Black Sea Bassfall_4.nc")

#longitude
lon <- ncvar_get(data, "xi", verbose = F)

#latitude
lat <- ncvar_get(data, "yi", verbose = F)

#thermal habitat projection
z <- ncvar_get(data, "zi")

#combine in data.frame
proj <- data.frame(lon = lon,
                   lat = lat,
                   z = z)

rm(data)
z.max <- 1.353462
proj <- proj %>% filter(z != "NA",z>0) %>% 
  mutate(z = plyr::mapvalues(z, from = (z[(z>z.max)]), to = rep(z.max,length(z[(z>z.max)]))))
proj$z <- proj$z/max(proj$z)
  
#turn dataframe to raster
coordinates(proj) = ~lon+lat
proj4string(proj)=crs # set it to lat-long
proj <- spTransform(proj,crs)
proj <- proj[strata,]
gridded(proj) <- TRUE
r <- raster(proj)
#projection(r) <- crs#downsample
d <- aggregate(r, fact=5)
# 
# ggplot(data=r_df,aes(Var2, rev(Var1), fill = value)) +
#   geom_tile() +
#   scale_fill_gradient2(low = "blue",mid = "white",high = "red",midpoint = 0.5)
r_spdf <- as(d, "SpatialPixelsDataFrame")
r_df <- as.data.frame(r_spdf)


m_df <- r_df %>%
  reshape2::melt(id = c("y","x")) %>%
  dplyr::rename(lat = y, long = x) %>%
  dplyr::select(-variable)# %>%


### Recenter ####
center <- 0 # positive values only

# getworld map
worldmap <- map_data ("world")

#center and filter
worldmap$long.recenter <- ifelse(worldmap$long < center - 180 , worldmap$long + 360, worldmap$long)
map <- worldmap %>% filter (long > -78, long < -50, lat > 30, lat <60)
  
#base + geom_tile
p <- ggplot(data = map, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group), fill="#f9f9f9", colour = "grey65")+
  coord_fixed(xlim = xlims, ylim = ylims) +  theme_bw() + 
  theme(legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        #axis.text.y = element_blank(),
        #axis.ticks = element_blank(), 
        panel.border = element_rect(colour = "black")) +
  geom_tile(data = m_df, aes(y = lat, x = long, fill = value)) +
  scale_fill_gradient2(low = "blue",mid = "white",high = "red",midpoint = 0.5)# +
#plotly
plt <- ggplotly(p) %>%
    layout(
      title = "Black Sea Bass Thermal Habitat",
      titlefont = list(size = 15),
      margin = list(b = 50, t = 50),
      autosize = F,
      width = 500,
      legend = list(x = 0.1, y = 0.9,
      bgcolor = "#E2E2E2",
      bordercolor = "#FFFFFF",
      borderwidth = 2)
    )
shiny::div(plt, align = "center")


```

<br>
<br>
<br>

```{r stacked bars, eval = F}
#### Adjust plot properties -------------------------------
adjustAxes <- 
  ggplot2::theme(axis.title   = element_text(size = 18),
                 axis.text    = element_text(size = 15),
                 plot.title   = element_text(size = 20))

ggplot <- function(...) { ggplot2::ggplot(...)  + 
    ggplot2::theme_bw() + 
    adjustAxes}


#### Plot stacked bar with cpts for single var ------------
plot_stackbarcpts_single <- function(YEAR, var2bar,
                                     x, xlab, ylab,
                                     titl,
                                     file_suffix,
                                     leg_font_size = 10,
                                     remove_leg = FALSE,
                                     leg_ncol = 1,
                                     wcpts = TRUE,
                                     wdashed = TRUE,
                                     height = 5.5,
                                     width = 8,
                                     filt = TRUE,
                                     label = label,
                                     y.text = y.text) {
  
  dat2bar <- data.frame(YEAR, var2bar,
                        x)
     dat2plot <-
    dat2bar %>%
    tidyr::gather(variable, value, -YEAR, -var2bar) %>%
    dplyr::mutate(var2bar = gsub(pattern      = "_", 
                                 replacement  = " ", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "Atl.", 
                                 replacement  = "ATLANTIC", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "Atl", 
                                 replacement  = "ATLANTIC", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "NS and combined", 
                                 replacement  = "", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = "YT", 
                                 replacement  = "Yellowtail", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = " GoM", 
                                 replacement  = " GOM", 
                                 x            = var2bar),
                  var2bar = gsub(pattern      = " by EPU", 
                                 replacement  = "", 
                                 x            = var2bar))

  p <-   
    ggplot(dat2plot,
           aes(x = YEAR)) +
    geom_bar(data = dat2plot %>% filter(value > 0),
             aes(y = value, fill = var2bar),
             stat = "identity") +
    geom_bar(data = dat2plot %>% filter(value < 0),
             aes(y = value, fill = var2bar),
             stat = "identity") +
    geom_hline(size = 0.3, aes(yintercept = 0)) +
    xlab(xlab) +
    ylab(ylab) +
    ggtitle(titl) +
    guides(fill = guide_legend(ncol = leg_ncol)) +
    theme(legend.text  = element_text(size = leg_font_size),
          legend.title = element_blank()) +
    annotate("text", label = label, x = 1980, y = y.text,size = 8, colour = "black")
  
  if(remove_leg) p <- p + theme(legend.position = "none")
  return(p)
  #print(p)
  
  #ggsave(plot = p,
  #       filename = "./productivity_all.eps",
  #       width = width,
  #       height = height)
}

bar_dat <-SOE.data.2018[grepl("by EPU",SOE.data.2018$Var) & SOE.data.2018$EPU == "MAB",]
stacked_bar <- plot_stackbarcpts_single(YEAR = bar_dat$Time,
                         var2bar = bar_dat$Var,
                         x = bar_dat$Value,
                         titl = "",
                         xlab = "",
                         ylab = "Small fish per large fish biomass (anomaly)",
                         height = 5.5,
                         width = 9,
                         filt = FALSE,
                         label = "",
                         y.text = 10)

ggplotly(stacked_bar) %>% layout(autosize = F, width = 650, title = "Grounfish Productivity", titlefont = list(size = 15))
```

```{r bennet}
load("data/Bennet_ind.Rdata")
load("data/Bennet_value.Rdata")
viy1 <- econ[econ$var == "viy1",]
viy2 <- econ[econ$var == "viy2",]
piy1 <- econ[econ$var == "piy1",]
piy2 <- econ[econ$var == "piy2",]

BI<-ggplot()+geom_bar(data=viy1, aes(x=YEAR, y=value, fill=indicator), stat="identity")+
  geom_bar(data=viy2, aes(x=YEAR, y=value, fill=indicator), stat="identity")+
  geom_bar(data=piy1, aes(x=YEAR, y=value, fill=indicator), stat="identity")+
  geom_bar(data=piy2, aes(x=YEAR, y=value, fill=indicator), stat="identity")+
  scale_fill_brewer(name="",palette = "Set2")+
  geom_line(data=biyear, aes(x=YEAR, y=revchange, colour="$"))+
  scale_colour_grey(name="")

plt <- ggplotly(BI) %>% layout(title = "Revenue Change ($2015), Price (PI) and Volume Indicator (VI)",
                        titlefont = list(size = 15),
                        annotations = list(
                                        list(x = 0.2 , y = 1.0,
                                             text = paste0("GB EPU 1964-2016 Compared to Average Year"),
                                             showarrow = F, xref='paper', yref='paper',
                                             font = list(size = 12))),
                        autosize = F,
                        width = 650,
                        yaxis = list(title = "VALUE $1,000,000 ($2015)", titlefont = list(size = 15)),
                        xaxis = list(title = "YEAR", titlefont = list(size = 15)))

shiny::div(plt, align = "center")
```

